name: Deploy

on:
  push:
    tags:
      - '*'
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build & Push
    steps:
      # 登录docker仓库
      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKER_IMAGENAME }}:${{ github.ref_name }}